### ISSUE TITLE
Remote: repository not found

### ISSUE THREAD

**Issue by astridpx** [TunisianEagles/SocialBox#48]
Cloning into 'tweetshell'...
Username for 'https://github.com': myusername
Password for 'https://myusername@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/thelinuxchoice/tweetshell.git/' not found
./install-sb.sh: line 26: cd: tweetshell: No such file or directory
chmod: cannot access 'tweetshell.sh': No such file or directory
chmod: cannot access 'install.sh': No such file or directory
sudo: ./install.sh: command not found

**Comment by astridpx** [comment]
I installed social box after i run ./install-sb.sh this command i got this error
 
How to fix this?

**Comment by FreRare** [comment]
Same problem for me..
The problem is that the repository that the installer is looking for no longer exists on github. (404 err)

Is there any other repos to get the tool from?
I cant find any, the installer always uses the same repo, no matter where you clone the socialbox repo from.
If there is please notice me!!

**Comment by FreRare** [comment]
Nevermind!
Try out cloning this repo (https://github.com/samsesh/SocialBox-Termux.git) , this installer works properly.

**Comment by zakzico** [comment]
remote: Repository not found.
fatal: repository 'https://github.com/samsesh/SocailBox-Ternux.git/' not found

Tried downloading it and not found. Anyone had the same problem?
